In [402]:
import numpy as np
import pandas as pd

In [403]:
lawinen = pd.read_csv('data/Allg_Lawinen_Abgänge.csv')

In [404]:
import datetime as dt

lawinen['DATUM'] = lawinen['DATUM'].apply(lambda x: dt.datetime.strptime(x,'%Y-%m-%d %H:%M:%S') if type(x)==str else pd.NaT)
lawinen['ZEIT'] = lawinen['ZEIT'].apply(lambda x: dt.datetime.strptime(x,'%Y-%m-%d %H:%M:%S') if type(x)==str else pd.NaT)
lawinen

,DATUM,ZEIT,Lawinen_Art,GRNR,Volumen,Wetter,WIND_RCHTG,WIND_GSCHW,Temperatur,Schneehoehe,Neuschnee,Gefahr,Bemerkung
0,1957-02-27 00:00:00,1899-12-30 00:00:00,Grundlawine,43.0,NaN,Schneefall schwach,S,2.0,-5.0,280.0,4.0,0.0,NaN
1,1967-03-21 00:00:00,1899-12-30 00:00:00,Staublawine,13.0,NaN,bewölkt,SW,3.0,-7.0,0.0,10.0,0.0,NaN
2,1967-04-05 00:00:00,1899-12-30 07:20:00,Staublawine,13.0,NaN,Schneefall mäßig,NE,6.0,-5.0,320.0,25.0,NaN,NaN
3,1970-02-04 00:00:00,1899-12-30 00:00:00,Staublawine,13.0,NaN,Schneefall mäßig,SE,2.0,-6.0,118.0,32.0,NaN,NaN
4,1970-02-22 00:00:00,1899-12-30 10:49:00,Staublawine,13.0,NaN,Schneetreiben,SE,3.0,-3.0,170.0,25.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4095,2022-02-03 00:00:00,2022-02-03 00:00:00,Lockerschneelawine trocken,9.0,mittel,0,NO,5.0,0.0,NaN,5.0,4.0,NaN
4096,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4097,2022-02-08 00:00:00,NaT,Schneebrettlawine trocken,33.0,mittel,bedeckt,SW,20.0,-7.0,175.0,21.0,3.0,NaN
4098,NaT,NaT,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4099,2022-02-08 00:00:00,NaT,Schneebrettlawine trocken,43.0,klein,bewölkt,270,5.7,-1.0,175.0,21.0,3.0,NaN

In [405]:
lawinen.sort_values(by=['DATUM','ZEIT'],inplace=True)
lawinen

,DATUM,ZEIT,Lawinen_Art,GRNR,Volumen,Wetter,WIND_RCHTG,WIND_GSCHW,Temperatur,Schneehoehe,Neuschnee,Gefahr,Bemerkung
3486,0208-01-22 00:00:00,NaT,Schneebrettlawine trocken,43.0,mittel,Schneefall mäßig,135,5.0,-3.0,152.0,20.0,4.0,NaN
3493,0208-01-24 00:00:00,NaT,Schneebrettlawine trocken,14.0,klein,wolkenlos,225,3.0,4.0,156.0,0.0,3.0,NaN
491,1944-01-04 00:00:00,1899-12-30 16:00:00,Schneebrettlawine trocken,15.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
317,1944-12-28 00:00:00,1899-12-30 10:30:00,Schneebrettlawine trocken,7.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
1212,1945-03-08 00:00:00,1899-12-30 22:00:00,Staublawine,25.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3520,NaT,NaT,Lockerschneelawine naß,10.0,mittel,bedeckt,225,3.0,7.0,160.0,0.0,2.0,NaN
3700,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2.0,150.0,NaN,NaN,NaN
3952,NaT,NaT,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4096,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4098,NaT,NaT,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [406]:
start = dt.datetime.strptime('1992-01-01 00:00:00', '%Y-%m-%d %H:%M:%S')
end = dt.datetime.strptime('2022-12-31 00:00:00', '%Y-%m-%d %H:%M:%S')
lawinen = lawinen.loc[(lawinen['DATUM'] > start) & (lawinen['DATUM'] < end)]
lawinen

,DATUM,ZEIT,Lawinen_Art,GRNR,Volumen,Wetter,WIND_RCHTG,WIND_GSCHW,Temperatur,Schneehoehe,Neuschnee,Gefahr,Bemerkung
291,1992-02-06 00:00:00,1899-12-30,Schneebrettlawine trocken,19.0,groß,Schneetreiben,NE,5.0,-5.0,129.0,20.0,34.0,NaN
353,1992-02-06 00:00:00,1899-12-30,Schneebrettlawine trocken,17.0,groß,Schneetreiben,N,5.0,-5.0,129.0,20.0,34.0,NaN
888,1992-02-06 00:00:00,1899-12-30,Schneebrettlawine trocken,21.0,groß,Schneetreiben,NE,5.0,-5.0,129.0,20.0,34.0,NaN
192,1992-02-13 00:00:00,1899-12-30,Schneebrettlawine trocken,30.0,mittel,bewölkt,SW,1.0,1.0,141.0,2.0,3.0,NaN
375,1992-02-13 00:00:00,1899-12-30,Schneebrettlawine naß,37.0,mittel,bewölkt,SW,1.0,1.0,141.0,2.0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4091,2022-02-03 00:00:00,NaT,Schneebrettlawine trocken,33.0,mittel,bedeckt,NO,1.0,-4.0,140.0,15.0,4.0,NaN
4092,2022-02-03 00:00:00,NaT,Schneebrettlawine trocken,15.0,gross,bedeckt,NO,1.0,-4.0,140.0,15.0,4.0,NaN
4093,2022-02-03 00:00:00,NaT,Schneebrettlawine trocken,28.0,mittel,bedeckt,NO,-4.0,-4.0,140.0,15.0,4.0,NaN
4097,2022-02-08 00:00:00,NaT,Schneebrettlawine trocken,33.0,mittel,bedeckt,SW,20.0,-7.0,175.0,21.0,3.0,NaN
4099,2022-02-08 00:00:00,NaT,Schneebrettlawine trocken,43.0,klein,bewölkt,270,5.7,-1.0,175.0,21.0,3.0,NaN

In [407]:
#lawinen_katalog = pd.read_csv('data/Allg_Lawinen_Katalog.csv')
#lawinen['Lawinen_Name'] = lawinen['GRNR'].apply(lambda x: lawinen_katalog.loc[lawinen_katalog['GRNR']==x]['Lawinenname'].values[0] if x <= 42 else 'Alle Lawinen')
#lawinen['Lawinen_Name']

In [408]:
kaplawstr = pd.read_csv('data/kaplawstr.csv')
#lawinen = pd.merge(lawinen, lawinen['Lawinen_Name'].apply(lambda x: kaplawstr.loc[kaplawstr['Lawinenstrich']==x]), left_index=True, right_index=True)
#lawinen
lawinen = pd.merge(lawinen, kaplawstr, left_on='GRNR', right_on='ID')
lawinen

,DATUM,ZEIT,Lawinen_Art,GRNR,Volumen,Wetter,WIND_RCHTG,WIND_GSCHW,Temperatur,Schneehoehe,...,exp5,exp6,exp7,xoff,yoff,Scale,ScaleW,ScaleH,OffX,OffY
0,1992-02-06 00:00:00,1899-12-30 00:00:00,Schneebrettlawine trocken,19.0,groß,Schneetreiben,NE,5.0,-5.0,129.0,...,NaN,NaN,NaN,400462.235231,224226.498170,6.867793,433,151,171,-44
1,1992-02-19 00:00:00,1899-12-30 00:00:00,Schneebrettlawine trocken,19.0,groß,wolkenlos,SW,1.0,-18.0,154.0,...,NaN,NaN,NaN,400462.235231,224226.498170,6.867793,433,151,171,-44
2,1992-04-28 00:00:00,1899-12-30 00:00:00,Lockerschneelawine naß,19.0,groß,bewölkt,S,14.0,2.0,167.0,...,NaN,NaN,NaN,400462.235231,224226.498170,6.867793,433,151,171,-44
3,1992-05-02 00:00:00,1899-12-30 00:00:00,Lockerschneelawine naß,19.0,groß,bewölkt,SW,5.0,-2.0,183.0,...,NaN,NaN,NaN,400462.235231,224226.498170,6.867793,433,151,171,-44
4,1992-05-03 00:00:00,1899-12-30 00:00:00,Lockerschneelawine naß,19.0,groß,bewölkt,SW,3.0,-1.0,172.0,...,NaN,NaN,NaN,400462.235231,224226.498170,6.867793,433,151,171,-44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2584,2021-12-04 00:00:00,1899-12-30 09:00:00,Staublawine,28.0,mittel,bedeckt,180,2.0,-1.0,74.0,...,NaN,NaN,NaN,401356.059692,226681.470933,8.296389,622,852,189,526
2585,2022-02-03 00:00:00,NaT,Schneebrettlawine trocken,28.0,mittel,bedeckt,NO,-4.0,-4.0,140.0,...,NaN,NaN,NaN,401356.059692,226681.470933,8.296389,622,852,189,526
2586,2013-04-21 00:00:00,NaT,Schneebrettlawine naß,5.0,mittel,wolkenlos,315,2.0,4.0,121.0,...,NaN,NaN,NaN,400147.298260,223483.021847,7.956891,449,397,319,275
2587,2018-04-20 00:00:00,NaT,Lockerschnee- und Schneebrettlawinen naß,9.0,klein,wolkenlos,5,2.0,12.0,110.0,...,NaN,NaN,NaN,399829.941089,223162.047562,8.805489,420,371,333,276
2588,2022-02-03 00:00:00,2022-02-03 00:00:00,Lockerschneelawine trocken,9.0,mittel,0,NO,5.0,0.0,NaN,...,NaN,NaN,NaN,399829.941089,223162.047562,8.805489,420,371,333,276

In [409]:
#polygon = pd.read_csv('data/polygon.csv')
#lawinen['Lawinen_Name'] = lawinen['Code_neu'].apply(lambda x: polygon.loc[polygon['LawID']==x]['Lawinenname'].values[0])
#lawinen['Lawinen_Name']

In [410]:
TOPP = pd.read_csv('data/TOPP.csv')
TOPP = TOPP.groupby('Lawinencode').first().reset_index()
lawinen = pd.merge(lawinen, TOPP, left_on='Code_neu', right_on='Lawinencode')
lawinen

,DATUM,ZEIT,Lawinen_Art,GRNR,Volumen,Wetter,WIND_RCHTG,WIND_GSCHW,Temperatur,Schneehoehe,...,MaxSun85,MaxSun99,MaxSun113,MaxSun127,MaxSun310,MaxSun324,MaxSun338,MaxSun352,HorÜb1,HorÜb2
0,1992-02-06 00:00:00,1899-12-30 00:00:00,Schneebrettlawine trocken,19.0,groß,Schneetreiben,NE,5.0,-5.0,129.0,...,7.2544,8.1873,9.2544,10.4576,4.1343,2.9064,2.1996,2.1219,NaN,NaN
1,1992-02-19 00:00:00,1899-12-30 00:00:00,Schneebrettlawine trocken,19.0,groß,wolkenlos,SW,1.0,-18.0,154.0,...,7.2544,8.1873,9.2544,10.4576,4.1343,2.9064,2.1996,2.1219,NaN,NaN
2,1992-04-28 00:00:00,1899-12-30 00:00:00,Lockerschneelawine naß,19.0,groß,bewölkt,S,14.0,2.0,167.0,...,7.2544,8.1873,9.2544,10.4576,4.1343,2.9064,2.1996,2.1219,NaN,NaN
3,1992-05-02 00:00:00,1899-12-30 00:00:00,Lockerschneelawine naß,19.0,groß,bewölkt,SW,5.0,-2.0,183.0,...,7.2544,8.1873,9.2544,10.4576,4.1343,2.9064,2.1996,2.1219,NaN,NaN
4,1992-05-03 00:00:00,1899-12-30 00:00:00,Lockerschneelawine naß,19.0,groß,bewölkt,SW,3.0,-1.0,172.0,...,7.2544,8.1873,9.2544,10.4576,4.1343,2.9064,2.1996,2.1219,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2584,2021-12-04 00:00:00,1899-12-30 09:00:00,Staublawine,28.0,mittel,bedeckt,180,2.0,-1.0,74.0,...,5.4714,7.1583,8.8874,9.6570,0.4521,0.1662,0.2313,0.1777,NaN,NaN
2585,2022-02-03 00:00:00,NaT,Schneebrettlawine trocken,28.0,mittel,bedeckt,NO,-4.0,-4.0,140.0,...,5.4714,7.1583,8.8874,9.6570,0.4521,0.1662,0.2313,0.1777,NaN,NaN
2586,2013-04-21 00:00:00,NaT,Schneebrettlawine naß,5.0,mittel,wolkenlos,315,2.0,4.0,121.0,...,4.7423,7.1546,8.2330,8.8186,0.0000,0.0000,0.0000,0.0000,NaN,NaN
2587,2018-04-20 00:00:00,NaT,Lockerschnee- und Schneebrettlawinen naß,9.0,klein,wolkenlos,5,2.0,12.0,110.0,...,6.6942,7.9091,8.5537,8.7603,2.2231,0.1322,0.0000,0.0000,NaN,NaN
2588,2022-02-03 00:00:00,2022-02-03 00:00:00,Lockerschneelawine trocken,9.0,mittel,0,NO,5.0,0.0,NaN,...,6.6942,7.9091,8.5537,8.7603,2.2231,0.1322,0.0000,0.0000,NaN,NaN

In [411]:
lawinen.to_csv('newData/lawinen_abgänge.csv', index=True)

In [412]:
mooser_wetter_daten = pd.read_csv('data/Mooser_Wetter_Daten.csv', sep=';')
mooser_wetter_daten

,Datum,Intervall,Lawinengrad,Lawinengrad_Norm,Lawinengrad_Gew,Schneehöhe,Schneehöhe_Norm,Schneehöhe_Gew,Niederschlag,Niederschlag_Norm,...,Neuschnee,Neuschnee_Norm,Neuschnee_Gew,Lawinenabgänge,Lawinenabgänge_Norm,Lawinenabgänge_Gew,Winterphase,Winterphase_Norm,Winterphase_Gew,Distanz
0,1956-11-29 00:00:00,1956/ 1957,0,0,0,113,215.978593,0,1.9,0,...,23.0,230,99999.0,0,0,0,0,0,0,7.995743e+07
1,1956-11-30 00:00:00,1956/ 1957,0,0,0,116,196.166855,0,2.5,0,...,7.0,70,99999.0,0,0,0,0,0,0,9.966613e+06
2,1956-12-01 00:00:00,1956/ 1957,0,0,0,124,225.198638,0,0.0,0,...,10.0,100,99999.0,0,0,0,0,0,0,9.966626e+06
3,1956-12-02 00:00:00,1956/ 1957,44,0,0,121,220.607735,0,2.5,0,...,0.0,0,144.0,0,0,0,0,0,0,3.750985e+02
4,1956-12-03 00:00:00,1956/ 1957,0,0,0,110,199.779857,0,11.0,0,...,2.0,20,37.0,0,0,0,0,0,0,3.575917e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9573,2022-02-08 00:00:00,2021/ 2022,33,0,0,175,162.359178,0,16.0,0,...,21.0,210,100.0,1,0,0,0,0,0,NaN
9574,2022-02-09 00:00:00,2021/ 2022,33,0,0,155,141.483293,0,8.0,0,...,0.0,0,240.0,0,0,0,0,0,0,NaN
9575,2022-02-10 00:00:00,2021/ 2022,33,0,0,149,134.537246,0,0.0,0,...,0.0,0,73.0,0,0,0,0,0,0,NaN
9576,2022-02-11 00:00:00,2021/ 2022,22,0,0,144,129.792371,0,0.0,0,...,0.0,0,21.0,0,0,0,0,0,0,NaN
9577,2022-02-12 00:00:00,2021/ 2022,22,0,0,149,132.381406,0,7.0,0,...,10.0,100,0.0,0,0,0,0,0,0,NaN

In [413]:
mooser_wetter_daten['Datum'] = mooser_wetter_daten['Datum'].apply(lambda x: dt.datetime.strptime(x,'%Y-%m-%d %H:%M:%S') if type(x)==str else pd.NaT)
mooser_wetter_daten = mooser_wetter_daten.loc[(mooser_wetter_daten['Datum'] > start) & (mooser_wetter_daten['Datum'] < end)]

In [414]:
lawinen['DATUM'] = pd.to_datetime(lawinen['DATUM'])


gesamt_df = pd.merge(mooser_wetter_daten, lawinen, right_on='DATUM', left_on='Datum', how='outer')
gesamt_df

,Datum,Intervall,Lawinengrad,Lawinengrad_Norm,Lawinengrad_Gew,Schneehöhe,Schneehöhe_Norm,Schneehöhe_Gew,Niederschlag,Niederschlag_Norm,...,MaxSun85,MaxSun99,MaxSun113,MaxSun127,MaxSun310,MaxSun324,MaxSun338,MaxSun352,HorÜb1,HorÜb2
0,1992-01-02,1991/ 1992,0.0,0.0,0.0,120.0,149.416342,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1992-01-03,1991/ 1992,0.0,0.0,0.0,120.0,144.796380,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1992-01-04,1991/ 1992,0.0,0.0,0.0,114.0,134.216336,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1992-01-05,1991/ 1992,0.0,0.0,0.0,110.0,131.490474,0.0,2.9,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1992-01-06,1991/ 1992,0.0,0.0,0.0,107.0,129.696970,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6542,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.9076,9.2070,9.3464,10.5391,4.3672,3.1589,3.5039,2.5625,NaN,NaN
6543,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.4714,7.1583,8.8874,9.6570,0.4521,0.1662,0.2313,0.1777,NaN,NaN
6544,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.2430,8.7778,9.9499,10.2503,4.6703,3.9328,4.1490,3.9756,NaN,NaN
6545,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.7126,10.0909,11.0894,11.4501,6.1862,5.3065,5.2478,5.0132,NaN,NaN
6546,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.4714,7.1583,8.8874,9.6570,0.4521,0.1662,0.2313,0.1777,NaN,NaN

In [415]:
gesamt_df.to_csv('newData/gesamt_set.csv', index=False)